M48
; DRILL file {KiCad 7.0.7-7.0.7~ubuntu22.04.1} date Mon Sep 25 23:33:45 2023
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2023-09-25T23:33:45+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.7-7.0.7~ubuntu22.04.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C2.000
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.200
%
G90
G05
T1
X69.6Y-40.6
X69.6Y-58.6
X69.6Y-76.6
X69.6Y-94.6
X78.4Y-40.6
X78.4Y-58.6
X78.4Y-76.6
X78.4Y-94.6
T2
X80.0Y-107.7
T0
M30
